# docker-compose.yml
version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
    
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
  
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_data:/staticfiles
      - media_data:/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data: