# Generated by Django 5.2 on 2025-05-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', 'new_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bienresponsabilite',
            options={'ordering': ['-date_affectation'], 'verbose_name': "Responsabilité d'un bien", 'verbose_name_plural': 'Responsabilités des biens'},
        ),
    ]
