# Generated by Django 5.2 on 2025-04-22 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilvehicule',
            name='assurance',
        ),
        migrations.RemoveField(
            model_name='profilvehicule',
            name='consommation',
        ),
        migrations.RemoveField(
            model_name='profilvehicule',
            name='immatriculation',
        ),
        migrations.RemoveField(
            model_name='profilvehicule',
            name='puissance',
        ),
        migrations.AddField(
            model_name='bien',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/'),
        ),
        migrations.AddField(
            model_name='profilvehicule',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilvehicule',
            name='date_derniere_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilvehicule',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilvehicule',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilvehicule',
            name='numero_chassis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilvehicule',
            name='prochaine_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='classe_risque',
            field=models.CharField(blank=True, choices=[('i', 'Classe I - Risque faible'), ('iia', 'Classe IIa - Risque modéré'), ('iib', 'Classe IIb - Risque élevé'), ('iii', 'Classe III - Risque critique')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='consommation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='contact_sav',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='contrat_maintenance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='date_derniere_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='date_installation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='departement_utilisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='duree_vie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='fin_garantie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='fournisseur_service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='frequence_maintenance',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='maintenance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='normes_applicables',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='organisme_certification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='parametres_techniques',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='pieces',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='source_energie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif - En service'), ('maintenance', 'En maintenance'), ('stockage', 'En stockage'), ('inutilisable', 'Hors service'), ('calibration', 'En calibration')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='type_equipement',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('therapeutique', 'Thérapeutique'), ('laboratoire', 'Laboratoire'), ('monitoring', 'Surveillance'), ('imagerie', 'Imagerie'), ('chirurgical', 'Chirurgical'), ('sterilisation', 'Stérilisation'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profilequipementmedical',
            name='utilisateurs_formes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='adresse_mac',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='capacite_stockage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='carte_graphique',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='contrat_maintenance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='date_derniere_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='date_derniere_maj',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='date_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='date_mise_service',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='fin_garantie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='logiciels',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='memoire_ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='nom_reseau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='prochaine_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='spec_tech',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='statut',
            field=models.CharField(choices=[('en_service', 'En service'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('en_attente', 'En attente de déploiement')], default='en_service', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='type_equipement',
            field=models.CharField(choices=[('ordinateur_fixe', 'Ordinateur fixe'), ('ordinateur_portable', 'Ordinateur portable'), ('serveur', 'Serveur'), ('imprimante', 'Imprimante'), ('scanner', 'Scanner'), ('photocopieur', 'Photocopieur'), ('reseau', 'Équipement réseau'), ('stockage', 'Solution de stockage'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profilinformatique',
            name='version_os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ProfilConsommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('unite', models.CharField(max_length=50)),
                ('stock_securite', models.PositiveIntegerField(default=0)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_consommable', to='patrimoine.bien')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilMobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiau', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=50)),
                ('fabricant', models.CharField(max_length=100)),
                ('annee_fabrication', models.PositiveIntegerField(blank=True, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_mobilier', to='patrimoine.bien')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut_juridique', models.CharField(max_length=255)),
                ('usage', models.CharField(blank=True, max_length=100)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_terrain', to='patrimoine.bien')),
            ],
        ),
    ]
