# Generated by Django 5.2 on 2025-04-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0002_remove_profilvehicule_assurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='departement',
        ),
        migrations.AddField(
            model_name='bien',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimoine.commune'),
        ),
        migrations.AddField(
            model_name='commune',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
