# Generated by Django 5.2 on 2025-04-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0003_remove_commune_departement_bien_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimoine.departement'),
        ),
    ]
