# Generated by Django 5.2 on 2025-04-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0004_commune_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='province',
            name='longitude',
        ),
    ]
