# Generated by Django 5.2 on 2025-04-25 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0005_remove_province_latitude_remove_province_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimoine.departement'),
        ),
    ]
